### PR TITLE
feat: add default clash for clash, surge and wireguard

### PR DESCRIPTION
**Pull request by CorrectRoadH**
# What does the PR do?
the PR adds three route `/clash`, `/surge` and `/wireguard`. requesting `/clash` equal `/api/clash?best=false&randomName=true` and etc. is same.

# What is the PR for?
default route has many advantages. Such as it can subscription clash proxy like `https://subs.zeabur.app/clash`. the url is very easy be remember.

### CODE REVIEW

**Comment by vvbbnn00** [comment]
I feel this is somewhat redundant. Actually, the code can be modified so that accessing an interface like `/api/clash` would imply default parameters.

**Comment by CorrectRoadH** [comment]
> I feel this is somewhat redundant. Actually, the code can be modified so that accessing an interface like `/api/clash` would imply default parameters.

No, if not pass the arg, the code`random_name = request.args.get('randomName').lower() == "true" or False
`,  will throw `NoneType not have lower() function`. I tried three ways : `extract logic to a new function`, `add args to httpClash` and `add if 'randomName' in request.args`. the current solution is simplest and most elegant.

**Comment by vvbbnn00** [comment]
> > I feel this is somewhat redundant. Actually, the code can be modified so that accessing an interface like `/api/clash` would imply default parameters.
> 
> No, if not pass the arg, the code`random_name = request.args.get('randomName').lower() == "true" or False `, will throw `NoneType not have lower() function`. I tried three ways : `extract logic to a new function`, `add args to httpClash` and `add if 'randomName' in request.args`. the current solution is simplest and most elegant.

Indeed, this is a logical bug that has been identified and will be addressed in a future update. The current interface, once the issue is resolved, should meet the present business requirements. Therefore, it is advisable to avoid adding extra interfaces.

**Comment by CorrectRoadH** [comment]
> Indeed, this is a logical bug that has been identified and will be addressed in a future update. The current interface, once the issue is resolved, should meet the present business requirements. Therefore, it is advisable to avoid adding extra interfaces.

Ok. I will wait your patch.👌

**Pull request closed without merging**
